#!/usr/bin/env python3
#
# Regenerates latex_fonts/embedded-fonts.css and
# latex_fonts/embedded-fonts-dev.css: the @font-face rules for the themes,
# each one carrying a subset of its own font inline as a data: URI.
#
# This is a maintainer's tool, not part of installation. Nothing runs it for
# you, and its output is committed, so nobody installing the theme needs
# Python or fonttools. Run it only after changing which faces the themes
# declare, or after replacing a bundled font file.
#
#   python3 -m venv /tmp/fontenv
#   /tmp/fontenv/bin/pip install fonttools brotli
#   /tmp/fontenv/bin/python scripts/build-embedded-fonts.py
#
# Why the fonts are inlined at all
# -------------------------------
# Typora's HTML export inlines the theme stylesheet as text, and before it
# does, it deletes every @font-face rule it finds:
#
#     .replace(/@font\-face\s*{[^}]+}\s*\n/g, "")
#
# (TypeMark/appsrc/main.js). So an exported HTML file has no theme faces at
# all and falls back to whatever the reader's system provides -- which is how
# an export ended up in Times, or worse, in whichever installed family sat
# next in the stack. PDF export is unaffected: it links the real CSS files
# instead of inlining them.
#
# Two things follow, and both are load-bearing:
#
# 1. Each rule ends `} /* export */` rather than `}`. The stripper is a
#    regular expression that wants whitespace and a newline straight after
#    the closing brace; a comment there is neither, so the rule survives into
#    the export. It is a deliberate leak through an exact regex. If a future
#    Typora parses CSS properly instead, the rules go back to being dropped
#    and exports return to system fallbacks -- no worse than before, and
#    nothing else in the theme depends on the trick.
#
# 2. Every face lists its local file first and the inlined subset second.
#    Typora rewrites the relative url() to an absolute file:// path on export,
#    so on the machine that did the exporting the browser loads the full font
#    off disk, with the complete glyph set. Anywhere else that path is a dead
#    end, the browser moves to the next source, and the subset takes over.
#
# The subset is what keeps the size honest: the full set of faces as WOFF2 is
# 4.3 MB, which is not something to paste into a stylesheet. Restricted to the
# ranges below it is a little over 1 MB, which every export then carries.
import base64
import os
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(REPO, "latex_fonts")

# What an exported document actually sets in these faces: Latin and its
# accents, combining marks, Greek including the polytonic ranges, the
# punctuation and dashes the theme's list markers and prose need,
# sub/superscripts, currency, letterlike forms,
# arrows, mathematical operators (the "*" list marker is U+2217), geometric
# shapes, and the fi/fl ligatures. Anything outside this -- Cyrillic, CJK,
# the rarer symbol blocks -- is left to the full font on disk and to the
# fallback stacks elsewhere.
TEXT_RANGES = ",".join([
    "U+0000-00FF",  # Basic Latin, Latin-1 Supplement
    "U+0100-017F",  # Latin Extended-A
    "U+0300-036F",  # Combining Diacritical Marks
    "U+0370-03FF",  # Greek and Coptic
    "U+1F00-1FFF",  # Greek Extended (the polytonic the demo sets)
    "U+2000-206F",  # General Punctuation
    "U+2070-209F",  # Super- and Subscripts
    "U+20A0-20BF",  # Currency Symbols
    "U+2100-214F",  # Letterlike Symbols
    "U+2190-21FF",  # Arrows
    "U+2200-22FF",  # Mathematical Operators
    "U+25A0-25FF",  # Geometric Shapes
    "U+FB00-FB06",  # Latin ligatures
])

# The backtick face exists to serve exactly one codepoint.
BACKTICK_RANGES = "U+0060"

HEADER = """/*
 * {name}
 *
 * Generated by scripts/build-embedded-fonts.py -- do not edit by hand.
 *
 * Every rule names its local font file first and carries a WOFF2 subset of
 * the same face inline as a data: URI second. The local file is what the
 * editor and a same-machine export use; the subset is what makes an exported
 * HTML file keep the theme's typefaces on someone else's machine.
 *
 * Subset coverage: Latin and Latin Extended-A, combining marks, Greek,
 * polytonic Greek, general punctuation, sub- and superscripts, currency,
 * letterlike symbols, arrows, mathematical operators, geometric shapes,
 * and the Latin ligatures.
 *
 * The `/* export *\\/` comment after each closing brace is not decoration.
 * Typora's HTML export deletes @font-face rules with a regular expression
 * that expects a newline after the brace, and the comment is what carries
 * these rules past it. See the script's header for the whole story.
 */
"""

# family, weight, style, source file, subset ranges (None keeps the whole font)
LATEX_FACES = [
    ("Backtick Serif Fix", 400, "normal", "NewCM10-Book.otf", BACKTICK_RANGES),
    ("Backtick Serif Fix", 700, "normal", "NewCM10-Bold.otf", BACKTICK_RANGES),
    ("Backtick Serif Fix", 400, "italic", "NewCM10-BookItalic.otf", BACKTICK_RANGES),
    ("Backtick Serif Fix", 700, "italic", "NewCM10-BoldItalic.otf", BACKTICK_RANGES),
    ("New Computer Modern Sans", 400, "normal", "NewCMSans10-Book.otf", TEXT_RANGES),
    ("New Computer Modern Sans", 700, "normal", "NewCMSans10-Bold.otf", TEXT_RANGES),
    ("New Computer Modern Sans", 400, "italic", "NewCMSans10-BookOblique.otf", TEXT_RANGES),
    ("New Computer Modern Sans", 700, "italic", "NewCMSans10-BoldOblique.otf", TEXT_RANGES),
    ("New Computer Modern Mono", 400, "normal", "NewCMMono10-Book.otf", TEXT_RANGES),
    ("New Computer Modern Mono", 700, "normal", "NewCMMono10-Bold.otf", TEXT_RANGES),
    ("New Computer Modern Mono", 400, "italic", "NewCMMono10-BookItalic.otf", TEXT_RANGES),
    ("New Computer Modern Mono", 700, "italic", "NewCMMono10-BoldOblique.otf", TEXT_RANGES),
    # Nastaliq is shaped, not composed: subsetting it by range would cut the
    # ligature and mark lookups Urdu depends on, and the whole face is 95 KB
    # as WOFF2 anyway, so it goes in complete.
    ("Noto Nastaliq Urdu", 400, "normal", "NotoNastaliqUrdu-Regular.ttf", None),
    ("New Computer Modern", 400, "normal", "NewCM10-Book.otf", TEXT_RANGES),
    ("New Computer Modern", 700, "normal", "NewCM10-Bold.otf", TEXT_RANGES),
    ("New Computer Modern", 400, "italic", "NewCM10-BookItalic.otf", TEXT_RANGES),
    ("New Computer Modern", 700, "italic", "NewCM10-BoldItalic.otf", TEXT_RANGES),
]

DEV_FACES = [
    ("JuliaMono", 400, "normal", "JuliaMono-Regular.ttf", TEXT_RANGES),
    ("JuliaMono", 700, "normal", "JuliaMono-Bold.ttf", TEXT_RANGES),
    ("JuliaMono", 400, "italic", "JuliaMono-RegularItalic.ttf", TEXT_RANGES),
    ("JuliaMono", 700, "italic", "JuliaMono-BoldItalic.ttf", TEXT_RANGES),
    ("iA Writer Mono", 400, "normal", "iAWriterMonoS-Regular.ttf", TEXT_RANGES),
    ("iA Writer Mono", 700, "normal", "iAWriterMonoS-Bold.ttf", TEXT_RANGES),
    ("iA Writer Mono", 400, "italic", "iAWriterMonoS-Italic.ttf", TEXT_RANGES),
    ("iA Writer Mono", 700, "italic", "iAWriterMonoS-BoldItalic.ttf", TEXT_RANGES),
]


def subset(source, ranges, out_path):
    args = [
        sys.executable, "-m", "fontTools.subset", source,
        "--layout-features=*",
        "--flavor=woff2",
        "--output-file=" + out_path,
    ]
    if ranges:
        args.append("--unicodes=" + ranges)
    else:
        args.append("--unicodes=*")
    subprocess.run(args, check=True, stdout=subprocess.DEVNULL)


def rule(family, weight, style, source_file, ranges, tmp):
    source = os.path.join(FONT_DIR, source_file)
    if not os.path.exists(source):
        sys.exit("Missing font file: " + source)
    fmt = "opentype" if source_file.endswith(".otf") else "truetype"
    out_path = os.path.join(tmp, source_file + "." + str(weight) + style + ".woff2")
    subset(source, ranges, out_path)
    with open(out_path, "rb") as handle:
        payload = base64.b64encode(handle.read()).decode("ascii")
    lines = [
        "@font-face {",
        '    font-family: "%s";' % family,
        "    src:",
        '        url("./%s") format("%s"),' % (source_file, fmt),
        '        url("data:font/woff2;base64,%s") format("woff2");' % payload,
        "    font-weight: %d;" % weight,
        "    font-style: %s;" % style,
        "    font-display: swap;",
    ]
    if ranges == BACKTICK_RANGES:
        lines.append("    unicode-range: U+0060;")
    lines.append("} /* export */")
    return "\n".join(lines), os.path.getsize(out_path)


def build(name, faces, out_file):
    total = 0
    blocks = []
    with tempfile.TemporaryDirectory() as tmp:
        for family, weight, style, source_file, ranges in faces:
            block, size = rule(family, weight, style, source_file, ranges, tmp)
            blocks.append(block)
            total += size
    body = HEADER.format(name=name) + "\n" + "\n\n".join(blocks) + "\n"
    with open(out_file, "w", encoding="utf-8") as handle:
        handle.write(body)
    print("%s: %d faces, %.1f KB of subset fonts, %.1f KB on disk" % (
        os.path.basename(out_file), len(faces), total / 1024.0,
        os.path.getsize(out_file) / 1024.0))


def main():
    build(
        "Embedded font faces for the LaTeX and LaTeX Dark themes",
        LATEX_FACES,
        os.path.join(FONT_DIR, "embedded-fonts.css"),
    )
    build(
        "Embedded font faces for the LaTeX Dev Dark theme",
        DEV_FACES,
        os.path.join(FONT_DIR, "embedded-fonts-dev.css"),
    )


if __name__ == "__main__":
    main()
